package com.celebtwit.dao;

import com.celebtwit.dao.hibernate.BasePersistentClass;
import com.celebtwit.dao.hibernate.HibernateUtil;
import com.celebtwit.session.AuthControlled;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4


/**
 * Userrole generated by hbm2java
 */

public class Listimportblock extends BasePersistentClass implements java.io.Serializable, AuthControlled {



    // Fields

     private int listimportblockid;
     private String twitterusername;




    public static Listimportblock get(int id) {
        Logger logger = Logger.getLogger("com.celebtwit.dao.Listimportblock");
        try {
            logger.debug("Listimportblock.get(" + id + ") called.");
            Listimportblock obj = (Listimportblock) HibernateUtil.getSession().get(Listimportblock.class, id);
            if (obj == null) {
                logger.debug("Listimportblock.get(" + id + ") returning new instance because hibernate returned null.");
                return new Listimportblock();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.celebtwit.dao.Listimportblock", ex);
            return new Listimportblock();
        }
    }

    // Constructors

    /** default constructor */
    public Listimportblock() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }


    public int getListimportblockid() {
        return listimportblockid;
    }

    public void setListimportblockid(int listimportblockid) {
        this.listimportblockid = listimportblockid;
    }



    public String getTwitterusername() {
        return twitterusername;
    }

    public void setTwitterusername(String twitterusername) {
        this.twitterusername = twitterusername;
    }
}