package com.celebtwit.dao;

import com.celebtwit.dao.hibernate.BasePersistentClass;
import com.celebtwit.dao.hibernate.HibernateUtil;
import com.celebtwit.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Set;
import java.util.HashSet;
import java.util.Date;
// Generated Apr 17, 2006 3:45:25 PM by Hibernate Tools 3.1.0.beta4



/**
 * User generated by hbm2java
 */

public class User extends BasePersistentClass implements java.io.Serializable, AuthControlled {


     private int userid;
     private boolean isenabled;
     private String email;
     private String password;
     private String firstname;
     private String lastname;
     private String nickname;
     private boolean isactivatedbyemail;
     private String emailactivationkey;
     private Date emailactivationlastsent;
     private Date createdate;
     private int chargemethod;
     private int chargemethodcreditcardid;
     private int facebookuserid;
     private boolean isfacebookappremoved;
     private Date facebookappremoveddate;
     private int exerciseeveryxminutes;
     private Date nextexercisetime;
     private String upcomingexercises;
     private int exercisechooserid;
     private int exerciselistid;
     private int currentexercisenum;


     //Association
    private Set<Userrole> userroles = new HashSet<Userrole>();





    public static User get(int id) {
        Logger logger = Logger.getLogger("com.celebtwit.dao.User");
        try {
            logger.debug("User.get(" + id + ") called.");
            User obj = (User) HibernateUtil.getSession().get(User.class, id);
            if (obj == null) {
                logger.debug("User.get(" + id + ") returning new instance because hibernate returned null.");
                return new User();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.celebtwit.dao.User", ex);
            return new User();
        }
    }

    // Constructors

    /** default constructor */
    public User() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }

    
    /** full constructor */
    public User(int userid, String email, String password, String firstname, String lastname) {
        this.userid = userid;
        this.email = email;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
    }
    

   
    // Property accessors


    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public boolean getIsenabled() {
        return isenabled;
    }


    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname=nickname;
    }

    public void setIsenabled(boolean isenabled) {
        this.isenabled = isenabled;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public boolean getIsactivatedbyemail() {
        return isactivatedbyemail;
    }

    public void setIsactivatedbyemail(boolean isactivatedbyemail) {
        this.isactivatedbyemail = isactivatedbyemail;
    }

    public String getEmailactivationkey() {
        return emailactivationkey;
    }

    public void setEmailactivationkey(String emailactivationkey) {
        this.emailactivationkey = emailactivationkey;
    }

    public Date getEmailactivationlastsent() {
        return emailactivationlastsent;
    }

    public void setEmailactivationlastsent(Date emailactivationlastsent) {
        this.emailactivationlastsent = emailactivationlastsent;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public int getChargemethod() {
        return chargemethod;
    }

    public void setChargemethod(int chargemethod) {
        this.chargemethod = chargemethod;
    }

    public int getChargemethodcreditcardid() {
        return chargemethodcreditcardid;
    }

    public void setChargemethodcreditcardid(int chargemethodcreditcardid) {
        this.chargemethodcreditcardid = chargemethodcreditcardid;
    }

    public int getFacebookuserid() {
        return facebookuserid;
    }

    public void setFacebookuserid(int facebookuserid) {
        this.facebookuserid = facebookuserid;
    }

    public boolean getIsfacebookappremoved() {
        return isfacebookappremoved;
    }

    public void setIsfacebookappremoved(boolean isfacebookappremoved) {
        this.isfacebookappremoved = isfacebookappremoved;
    }

    public Date getFacebookappremoveddate() {
        return facebookappremoveddate;
    }

    public void setFacebookappremoveddate(Date facebookappremoveddate) {
        this.facebookappremoveddate = facebookappremoveddate;
    }

    public Set<Userrole> getUserroles() {
        return userroles;
    }

    public void setUserroles(Set<Userrole> userroles) {
        this.userroles = userroles;
    }



    public int getExerciseeveryxminutes() {
        return exerciseeveryxminutes;
    }

    public void setExerciseeveryxminutes(int exerciseeveryxminutes) {
        this.exerciseeveryxminutes = exerciseeveryxminutes;
    }

    public Date getNextexercisetime() {
        return nextexercisetime;
    }

    public void setNextexercisetime(Date nextexercisetime) {
        this.nextexercisetime = nextexercisetime;
    }

    public String getUpcomingexercises() {
        return upcomingexercises;
    }

    public void setUpcomingexercises(String upcomingexercises) {
        this.upcomingexercises = upcomingexercises;
    }

    public int getExercisechooserid() {
        return exercisechooserid;
    }

    public void setExercisechooserid(int exercisechooserid) {
        this.exercisechooserid = exercisechooserid;
    }

    public int getExerciselistid() {
        return exerciselistid;
    }

    public void setExerciselistid(int exerciselistid) {
        this.exerciselistid = exerciselistid;
    }

    public int getCurrentexercisenum() {
        return currentexercisenum;
    }

    public void setCurrentexercisenum(int currentexercisenum) {
        this.currentexercisenum = currentexercisenum;
    }


    
}
